[property]
#dewarp-dump-frames=10
output-width=1728
output-height=2752

#########################################
# Note - Max 4 surfaces are supported
#########################################

[surface0]
# 1=PushBroom, 2=VertRadCyl, 3=PerspectivePerspective
projection-type=3
width=1728
height=2752
focal-length=1100
#src-fov=100
#top-angle=30
#bottom-angle=-30
#distortion=-0.09;0;0;0;0
distortion=-0.09000;0.00000;0.00000;0.00000;0.00000
#src-x0=864
#src-x0=1100
#src-y0=1376
#roll=4
#yaw=-4
#src-x0=1861.88
#src-y0=1216.04
# 0=cudaAddressModeClamp, 1=cudaAddressModeBorder
# cuda-address-mode=0
